version: '3'
services:
    
  php:
    build: ./images/php-fpm
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./images/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir:
      /var/www
      
  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./:/var/www
      - ./pocket_calculator:/usr/share/nginx/html
      - ./images/nginx:/etc/nginx/conf.d
    working_dir:
      /var/www
      
  mysql:
    image: mysql:5.7
    ports: 
      - "3336:3306"
    volumes:
      - data:/var/lib/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pocket_calculator
      MYSQL_USER: pocket_calculator
      MYSQL_PASSWORD: password
volumes:
  data: